Give up connecting to database after trying 100 times

diff --git a/5.1/apache-php5/docker-ilias-entrypoint b/5.1/apache-php5/docker-ilias-entrypoint
--- a/5.1/apache-php5/docker-ilias-entrypoint
+++ b/5.1/apache-php5/docker-ilias-entrypoint
@@ -146,7 +146,14 @@ if [ ! -d "${ILIAS_DATA_PATH}/${ILIAS_CLIENT_NAME}" ]; then
         ${ILIAS_DB_NAME}"
 
     # Wait for database
+    tries=0
     until ${mysql} -e "SELECT VERSION();" &> /dev/null; do
+        tries=$((tries + 1))
+        if [ tries -gt 100 ]; then
+            # give up
+            echo "Could not connect to database, aborting"
+            exit 1
+        fi
         echo "Cannot connect to database, waiting"
         sleep 1
     done
